name: CheckOut  # このworkflowの名前

on: # onで実行タイミングを設定
  workflow_dispatch: # 手動で実行するAction
  push:
    branches: main

jobs:
  hello-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Run echo command
        run: echo Hello, world! # Hello World!と出力する
